ci(github): switch to github ci
SocialGouv/archifiltre pull request #1098
Opened 2020-10-28 12:36 UTC by douglasduteil

<img src=https://media.giphy.com/media/8gwgQZR82xB2o/giphy.gif width=100%>

2020-10-28 13:01 UTC, Alezco requested changes
Cool cette mise à jour !

2020-10-28 13:04 UTC, douglasduteil commented on .github/workflows/ci.yml
> +      - name: Set up Node.js 12.x
yes.

2020-10-28 13:05 UTC, Alezco approved these changes

2020-10-28 13:11 UTC, cberthou commented
C'est normal qu'on fasse tous les jobs 2 fois (push et PR) ?

2020-10-28 14:14 UTC, douglasduteil commented
@cberthou 

> C'est normal qu'on fasse tous les jobs 2 fois (push et PR) ?


Il y a un test de merge pour la pr et un test sur le commit pour la branche

2020-10-28 14:15 UTC, cberthou approved these changes

2020-10-28 14:17 UTC, cberthou requested changes
Euh, j'ai approuvé, mais pas convaincu par les builds en fait, je recheck.

2020-10-28 14:20 UTC, cberthou commented
On a plus le build de la branche master et la possibilité de déclencher le packaging des versions pour les différentes plateformes, si ?

2020-10-28 15:19 UTC, douglasduteil commented
Il est pas fini le build @cberthou 
Il y a un build spécial mac ?

2020-10-28 15:41 UTC, cberthou commented
> Il est pas fini le build @cberthou
> Il y a un build spécial mac ?

Il n'était pas dans la CI, parce qu'il faut le lancer sur mac, mais oui. (`yarn mac`, la commande)

2020-10-28 16:01 UTC, Alezco commented
Au total, il y a 6 commandes pour les 6 artefacts à builder :
- `yarn win64` : Windows 64-bits
- `yarn win32` : Windows 32-bits
- `yarn win64-msi` : Un MSI pour Windows 64-bits
- `yarn win32-msi` : Un MSI Windows 32-bits
- `yarn mac` : MacOS
- `yarn linux` : Linux

2020-10-29 09:32 UTC, douglasduteil commented
euh... wat ?
![image](https://user-images.githubusercontent.com/730511/97550481-03a67800-19d2-11eb-92c5-d74b49c4b8a0.png)

<img src=https://media.giphy.com/media/07bZcm6oFFzvGhY2qd/giphy.gif width=100%>

2020-10-29 15:29 UTC, douglasduteil commented
![image](https://user-images.githubusercontent.com/730511/97595300-db377180-1a03-11eb-977f-eeef66c6da22.png)

@Alezco @cberthou ils me semblent un peu gros les binaires nan ?
J'ai mise trop de fichier dans les archives ?

2020-10-29 16:46 UTC, Alezco approved these changes

2020-10-29 17:03 UTC, Alezco commented
@douglasduteil En comparant avec la taille des artefacts de la dernière release (https://github.com/SocialGouv/archifiltre/releases/tag/v3.1.0), tout semble ok sauf pour les 2 msi qui sont quasiment deux fois plus gros. Enfin, le binaire electron-dist n'est peut-être pas nécessaire à stocker comme artefact

2020-11-02 09:34 UTC, cberthou commented
Par contre, le job de build de tous les assets a juste besoin d'être déclenché lorsqu'on tag une version, pas besoin de le faire sur chaque branche ou à chaque merge sur master. A chaque merge sur master, il nous faut la version windows x64 (et pourquoi pas à chaque PR, à la limite).

2020-11-02 09:37 UTC, Alezco commented
Et si on veut améliorer encore cette PR, on pourrait aussi lier ces artefacts à une release GitHub quand on tag un commit

2020-11-02 09:41 UTC, cberthou commented
> Et si on veut améliorer encore cette PR, on pourrait aussi lier ces artefacts à une release GitHub quand on tag un commit

Dans une autre PR. Je pense que dans un premier temps, on essaie d'avoir fonctionnellement la même chose qu'avec Gitlab.

2020-11-02 10:37 UTC, douglasduteil commented
@Alezco @cberthou On est loin d'une v1 sur ce switch vers github ?

BTW la version linux ne tourne pas sur mon Arch Linux...
![image](https://user-images.githubusercontent.com/730511/97858606-af680480-1cff-11eb-9022-16f27fb6efe6.png)

2020-11-02 10:44 UTC, Alezco commented
@douglasduteil Si les artefacts ne sont pas build à chaque PR/merge master, pour moi c'est bon :) Pour Archifiltre qui ne tourne pas sur Archlinux, j'avoue qu'on a testé que sur Ubuntu :/

2020-11-03 10:51 UTC, douglasduteil commented
>  Si les artefacts ne sont pas build à chaque PR/merge master, pour moi c'est bon

@Alezco 
Ah je dois désactiver le build des binaires sur les prs et les branches ? 



> Pour Archifiltre qui ne tourne pas sur Archlinux, j'avoue qu'on a testé que sur Ubuntu :/

Ok. Vous confirmez que les artefacts produit par cette pr fonctionne sur Ubuntu / Mac / Windows ?

2020-11-03 11:27 UTC, Alezco commented
@douglasduteil Alors il y a 2 cas : 
- A chaque merge sur master, on veut build uniquement l'artefact Windows 64 bits pour avoir un lien d'une version de test
- Manuellement (ou peut-être automatiquement plus tard), on voudra pouvoir builder les 6 artefacts pour une release (tous les 3 mois environ)

2020-11-04 10:15 UTC, cberthou commented
Il y avait une typo dans la commande de build du renderer. J'ai fix, on attend de voir.

2020-11-09 14:02 UTC, douglasduteil commented
> A chaque merge sur master, on veut build uniquement l'artefact Windows 64 bits pour avoir un lien d'une version de test

@Alezco On est posté ce lien ?

2020-11-09 14:58 UTC, douglasduteil commented
On master : 
![image](https://user-images.githubusercontent.com/730511/98557343-60dcdc00-22a4-11eb-
9766-3ac211f9f73d.png)

2020-11-10 08:10 UTC, cberthou approved these changes

2020-11-10 08:11 UTC, cberthou commented
Bon, bah on y va pour le merge ?

2020-11-10 08:51 UTC, Alezco commented
@douglasduteil C'est ok pour moi aussi

2020-11-10 15:14 UTC, merged