feat(github): add workflow_dispatch
SocialGouv/archifiltre pull request #1120
Opened 2020-11-12 15:33 UTC by douglasduteil

<img width=100% src=https://media.giphy.com/media/9LCQwVZaNs8N5W8Hu7/giphy.gif />

--- 

- [ ] should be able to release beta versions
- [ ] should be able to trigger release through github actions

2020-11-13 15:01 UTC, douglasduteil commented
@cberthou it closes #1121

2020-11-13 15:29 UTC, Alezco requested changes

2020-11-13 15:29 UTC, Alezco commented on .github/workflows/ci.yml
> +          npx semantic-release --plugins @semantic-release/commit-analyzer @semantic-release/npm
A ajouter dans les devDepencies et dans une commande yarn pour gagner un peu de temps d'exécution et de lisibilité ?

2020-11-13 15:29 UTC, Alezco commented on .github/workflows/ci.yml
> +          echo "::set-output name=next_version::${version}"
👍

2020-11-13 15:29 UTC, Alezco commented on package.json
> +  "version": "3.2.0-beta.6",
Si je comprends bien, chaque changement de ce champ dans une PR provoquera une nouvelle release ?

2020-11-13 15:30 UTC, Alezco commented
Also closes https://github.com/SocialGouv/archifiltre/pull/1095 and https://github.com/SocialGouv/archifiltre/pull/1010

2020-11-16 16:11 UTC, douglasduteil commented on package.json
> +  "version": "3.2.0-beta.6",
les changements dans une branches alpha, beta, next, master, vX.Y.Z provoquera une nouvelle release see  [semantic-release](https://github.com/semantic-release/semantic-release)

2020-11-16 16:13 UTC, douglasduteil commented on .github/workflows/ci.yml
> +          npx semantic-release --plugins @semantic-release/commit-analyzer @semantic-release/npm
si on les ajoutes dans les `devDepencies` on va perdre du temps à l'installation dans tous les commits qui ne release pas :(

2020-11-16 16:13 UTC, douglasduteil commented
@Alezco ready to merge ✅

2020-11-16 16:19 UTC, Alezco commented
@douglasduteil C'est ok pour moi. @cberthou ?

2020-11-16 16:19 UTC, Alezco approved these changes

2020-11-17 08:59 UTC, douglasduteil commented
Allez :)

2020-11-17 08:59 UTC, merged