Fix memory overload when working with large data sets
SocialGouv/archifiltre pull request #1157
Opened 2021-01-19 15:26 UTC by cberthou

2021-01-21 18:48 UTC, Alezco requested changes

2021-01-21 18:48 UTC, Alezco commented on src/util/file-tree-loader/load-from-filesystem-serializer.test.ts
> +      acc[`${index}`] = element;
```suggestion
      acc[index] = element;
```

2021-01-21 18:48 UTC, Alezco commented on src/util/file-tree-loader/load-from-filesystem-serializer.test.ts
> +      version: "3.1.1",
Utiliser la version de `package.json` ?

2021-01-21 18:48 UTC, Alezco commented on src/util/file-tree-loader/load-from-filesystem-serializer.ts
> +export const serializeField = (element: {
Ajouter de la JSDoc ?

2021-01-22 11:29 UTC, cberthou commented on src/util/child-process-stream/child-process-stream-messages.ts
> +  public averageLastModified: number;
Il existe toujours et est toujours calculé. Ce n'est pas le moment pour l'enlever. Je crée un ticket de dette technique.

2021-01-22 11:34 UTC, cberthou commented on src/util/child-process-stream/child-process-stream.ts
> +  console.log(sentSize);
je l'ai gardé de côté parce que je voulais utiliser cette donnée pour faire une progression du transfert.

2021-01-22 11:34 UTC, cberthou commented on src/util/file-tree-loader/load-from-filesystem-serializer.test.ts
> +      acc[`${index}`] = element;
Non, non, il faut le transformer en string.

2021-01-22 11:35 UTC, cberthou commented on src/util/file-tree-loader/load-from-filesystem-serializer.test.ts
> +      version: "3.1.1",
C'est un test. Il vaut mieux une valeur fixe.

2021-01-22 12:24 UTC, Alezco approved these changes

2021-01-22 12:53 UTC, merged